### ISSUE TITLE
Simplier count(*)

### ISSUE THREAD

**Issue by rodo** [jbranchaud/til#1]
In
https://github.com/jbranchaud/til/blob/master/postgres/count-records-by-type.md

I prefer ```select type, count(*) from table group by 1``` as is if the elements counted are something like ```select substring(unnaccent(upper('firstname',1,2))) ....``` there are less character to type at the end of the command :)

**Comment by jbranchaud** [comment]
@rodo good tip! I also try to use the indexes when ordering.

**Comment by rodo** [comment]
It's just an alias, here if you have an index on `type` it will be used.
