### ISSUE TITLE
go/not-so-random.md

### ISSUE THREAD

**Issue by lunixbochs** [jbranchaud/til#10]
For security reasons you probably shouldn't have a boilerplate to seed a random number generator with predictable/structured input like the current time (which can be guessed by an attacker). Use `crypto/rand` to seed your RNG.

It's also possible to recover the state of most PRNGs using the output, so you should usually just use `crypto/rand` directly for your random data until the RNG becomes your program's bottleneck.

**Comment by jbranchaud** [comment]
@lunixbochs interesting. I'll have to look in to `crypto/rand`. Thanks for sharing.
