### ISSUE TITLE
JS: Truthiness of Integer Arrays

### ISSUE THREAD

**Issue by ramadis** [jbranchaud/til#17]
Hey! The issue you are seeing there with [0] is not an issue at all. The behaviour is completley normal if you embrace JS coercion (implicit casting) in `==` operator.

the issue is that  in the expression `[0] == false`, `false` is actually coerced to a Number by the built-in object `Number`, and of course: `Number(false)` is 0!
Then, `[0]` is first coerced to the String `"0"` and finally coerced to the Number `0`.
So, the last comparision is actually 0 === 0. Which is obviously true.

Hope the explanation shed some light on the subject!

**Comment by jbranchaud** [comment]
Thanks for walking through the coercion rules. This makes more sense now. I don't think I can *embrace* JS coercion rules though 😉
