### ISSUE TITLE
List filenames without the diffs

### ISSUE THREAD

**Issue by cletusw** [jbranchaud/til#2]
For [List filenames without the diffs](https://github.com/jbranchaud/til/blob/master/git/list-filenames-without-the-diffs.md), I find that `--stat` is better than `--name-only` because it at least gives you a quick count of changes/deletions per file while still keeping the one-line-per-file format.

**Comment by jbranchaud** [comment]
@cletusw thanks for the tip, I didn't know about `--stat`.
