### ISSUE TITLE
vim "Wrap With Some Room" precision

### ISSUE THREAD

**Issue by mcrapet** [jbranchaud/til#32]
Hi,

It's a small issue in:
til / vim / Wrap With Some Room

This will not work with a vanilla vim.
It requires this plugin:
https://github.com/tpope/vim-surround

You should mention it.
Thanks!

**Comment by olshevskiy87** [comment]
but there is a mention about vim-surround in the beginning

> The surround.vim plugin allows you to wrap text objects ...

**Comment by mcrapet** [comment]
Shame on me! A link should be nice however.

**Comment by jbranchaud** [comment]
@mcrapet linking to it is a good idea, any interest in submitting a PR?

**Comment by mcrapet** [comment]
Hehe sure :)
