### ISSUE TITLE
javascript/create-an-array-containing-1-to-n.md

### ISSUE THREAD

**Issue by alokmenghrajani** [jbranchaud/til#6]
Simpler solution:
`Array(9).fill().map((_, y) => y+1)`

Or `(Array(10)+"").replace(/,/g,(_,y)=>y+1)`

**Comment by Dru89** [comment]
`Array.prototype.fill` doesn't have great support, though:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

**Comment by alokmenghrajani** [comment]
TIL :)

**Comment by graphnode** [comment]
Perhaps `Array.apply(null, Array(10)).map((n, i) => i)` 
or `Array.apply(null, Array(10)).map(function (n, i) { return i; })` for javascript engines that don't support the arrow functions.

**Comment by wltsmrz** [comment]
`Array.from({length: 10}, (_, i) => i + 1)` is also cool

**Comment by wmonk** [comment]
`const range = len => Array.from(Array(len)).map((_, i) => ++i)` will work too

**Comment by jbranchaud** [comment]
Thanks for all the input, I didn't realize there were so many ways to achieve this.
