### ISSUE TITLE
go/sleep-for-a-duration.md

### ISSUE THREAD

**Issue by Merovius** [jbranchaud/til#8]
It's not correct to say that [time.Sleep](https://golang.org/pkg/time/#Sleep) takes Nanoseconds. It takes a [time.Duration](https://golang.org/pkg/time/#Duration) as you can see from the signature. Go is strongly typed, so [you can't pass an int in there at all](http://play.golang.org/p/Aw9AqfoI9d).

The confusion is created by the way go handles untyped constants like integer-literals: They don't have a type and arbitrary precision and they get a type inferred at the place they are used. If you use it as an integer-type, like `int`, `uint32`, `rune`… or `time.Duration`, then that's the inferred type. That's how `time.Sleep(42)` can work - 42 is then inferred to be a `time.Duration`. However, that's more an unlucky consequence of the design, than intention. If no type can be inferred - for example when assigning it to a new variable, like `x := 42` - a default type (`int` for integer literals) is used, which is why above link creates a compiler-error.

I acknowledge that the exact details are hard to get right for "outsiders" not familiar with the language, but I just thought I should report that that statement isn't correct, technically :) It's not that `time.Sleep` takes nanoseconds, it just that a `time.Duration` is *stored* as an integer type with nanosecond granularity, so that's how an integer literal in place of a Duration is interpreted.

**Comment by jbranchaud** [comment]
@Merovius thanks for the clarifications. What you said above makes a lot of sense.
